### ISSUE TITLE
Source for flicd?

### ISSUE THREAD

**Issue by soumya92** [50ButtonsEach/fliclib-linux-hci#13]
Providing source code for flicd would be great!
- Allow users to write single purpose programs without needing to keep a server running.
- Could build flicd for arm7 or aarch64.
- Could build with an up-to-date libcurl (Currently fails to run on arch with `libcurl.so.4: version `CURL_OPENSSL_3' not found`)
- Audit the source code, suggest security and performance improvements
- Use GitHub for its intended purpose ;)

**Comment by findkiko** [comment]
I'm also unable to run flicd (libcurl4) on arch linux RasPi.

Could we maybe get a statically compiled flicd binary in the interim?

**Comment by Emill** [comment]
What's the error message you get?

**Comment by findkiko** [comment]
➜  [mopi] armv6l git:(master) ✗ sudo ./flicd
./flicd: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./flicd)
➜  [mopi] armv6l git:(master) ✗ ls /usr/lib/libcur*
/usr/lib/libcurl.so    /usr/lib/libcurl.so.4.4.0  /usr/lib/libcursesw.so
/usr/lib/libcurl.so.4  /usr/lib/libcurses.so
➜  [mopi] armv6l git:(master) ✗ uname -a
Linux mopi 4.1.17-4-ARCH #1 SMP Mon Feb 15 18:36:03 MST 2016 armv7l GNU/Linux

**Comment by Emill** [comment]
Could you try the latest release? It doesn't need libcurl anymore.

**Comment by findkiko** [comment]
Sorry for the belated response, but yes the latest release runs cleanly on armv7l (raspi2) archlinux.

**Comment by wschlich** [comment]
flicd should REALLY be FOSS'ed! it's a shame that this is is only available as a precompiled binary blob.

**Comment by wschlich** [comment]
@shortcut labs: Still no intentions to open-source flicd? :( Issues like #58 and #59 could easily be fixed with flicd being FOSS... *sigh*

**Comment by dennisdegreef** [comment]
I'd also like the source code being available, so I can implement it on exotic chips that are not predistributed. Chips like the ESP32 have bluetooth support.

**Comment by eric-johnson** [comment]
This is a big let-down. I was about to buy a few of these because of Linux & Mac support, but I didn't realize it wasn't open source. This, combined with #58/#59 has me reconsidering. My other WiFi IoT devices, though expecting to have an internet connection, work fine without them over a LAN with no internet access.

**Comment by aa4re** [comment]
Source Code please

**Comment by wschlich** [comment]
Seems Shortcut Labs is more committed to making money selling their flic hubs than to serve existing flic customers who wish to run a custom solution similar to their new product.

**Comment by fabianbergmark** [comment]
We are a small team, and any time we spend not working on the hub will further push our delivery date. The source code contains our (for now) proprietary protocol so that's why we are hesitating to release it. We'll have a talk today and see where we stand!

**Comment by wschlich** [comment]
@fabianbergmark I see. Looking forward! (I'm both a flic + flicd user and a flic hub backer, but I wish to continue using flicd on the RPi for the solutions I built with it in the office for lots of reasons).

**Comment by fabianbergmark** [comment]
@wschlich unfortunately we decided against it as it would reveal too much to potential competitors. However, we will continue to maintain flicd and after the hub release we can look into implementing requested features.

**Comment by wschlich** [comment]
@fabianbergmark that's sad ;'-( can you imagine moving that proprietary secret protocol stuff into an external binary blob libary that could be loaded by an open-source flicd that could thus be easily recompiled if needed?

**Comment by soumya92** [comment]
>  it would reveal too much to potential competitors
You mean someone else would be able to make better buttons that work with flic? Or someone else could make a better flic hub?

I'm disappointed that you're not confident enough in your product's merits that you have to hide it behind some proprietary b.s.

I own a few buttons, why can't I do with them what I please? That's very much against what I believed this product would be. If I wanted a locked down button, I would have just bought the cheaper POP buttons.

**Comment by rkeene** [comment]
@soumya92 Any suggestions on a specific replacement for the flic buttons ?

**Comment by soumya92** [comment]
No specific details, but if you just search for "Bluetooth media controls" you should easily find many options. The ones I use are circular with play/pause in the centre and volume/track controls on the outside.

**Comment by soumya92** [comment]
And to be fair, the Flic 2 Kickstarter suggested that this won't be an issue with the new version, so I'm eagerly waiting for the new buttons. So if you like the feel and size of the flics, then maybe you want to try out the new ones.

**Comment by ristomatti** [comment]
@soumya92 Also to be fair at least this repo still exists and I've been using it both on a Raspberry Pi 3 and an Odroid C2 running ARMv8 (to which I was kindly provided a binary for #62) with very little issues for two years now.

The problem with flicd hogging the Bluetooth adapter can be solved by buying a BT dongle. In fact if some of the recommended ones is bought, it can support many more buttons. 

For me the battery life on the buttons themselves has turned out to be the biggest grief. It's too common in this household to push a button that's supposed to ring your lost phone when you're in a hurry, only to find the battery has died. I don't know if this has been improved with the newer design but this still being closed source with development on halt, I can't see myself buying any new ones. I've also found a more lo-fi approach of using 433MHz wall light switches works better for me. The communication is not secure, the buttons aren't tiny but the range is great and batteries last forever.
