### ISSUE TITLE
Add Battery level to messages

### ISSUE THREAD

**Issue by Roaders** [50ButtonsEach/fliclib-linux-hci#17]
Can we add the battery level of the flic to the message that the library sends?

I saw in the phone app that battery level is now reported and this would be useful - we can send an email when battery level gets below a certain level for example.

I assume though that this might only work with the buttons with update-able firmware? :-(

**Comment by Emill** [comment]
This is on our todo list!
The battery level can be obtained for all firmwares, although the
estimation is better on later firmwares.
Den 8 jun 2016 09:33 skrev "Roaders" <notifications@github.com>:

**Comment by Roaders** [comment]
Brilliant :+1:

**Comment by devbobo** [comment]
@Emill any update on this ? I've had some issues with my flics chewing through the batteries (which I think I've resolved)...but having the battery level available would really help to monitor.

Thanks,

David

**Comment by Emill** [comment]
Hello, first of all can you explain a bit more about the battery issues? Are they draining faster than expected?

Regarding battery monitor we have just not had the time implementing it yet. Hopefully we'll have time soon.

**Comment by devbobo** [comment]
The battery draining was entirely my fault, during testing my app I put a call `connectController` inside the `close` event handler to see if that reconnected the button after it disconnected itself...and then subsequently forgot about it :)

**Comment by Sawtaytoes** [comment]
I'd like a way to monitor the battery levels too. I was going through the Node.js library and realized there wasn't a method for it, but I know the Flic devices themselves are battery-level aware.

Also, if later firmwares are better at monitoring battery levels, is there a way to upgrade Flic's firmware through the Linux SDK rather than through the Flic app itself? My buttons are tied to Raspberry Pis, and I can't qualify the time to upgrade firmware on 40+ devices individually through the Flic app especially when they're spread all throughout my house. Honestly, I don't even know how I'd disassociate a button with the SDK's SQLite db either.

**Comment by Sawtaytoes** [comment]
Looks like, after going through the source code, button color and a battery state listener were added. I might have to modify the Node.js API to hook in, but it looks like those methods are now available.

I still don't know how I'd handle firmware updates though.
